/*
 * Oper_Activity_Def.h
 *
 *  Created on: 2014年2月18日
 *      Author: xiaoliang
 */

#ifndef OPER_ACTIVITY_DEF_H_
#define OPER_ACTIVITY_DEF_H_

typedef boost::unordered_map<uint32_t, Time_Value> UInt_Time_Map;
typedef boost::unordered_map<uint32_t, UInt_Time_Map> UInt_UInt_Time_Map;

enum OPER_ACTIVITY_ITEM_TYPE {
	OPER_ACTIVITY_ITEM_HONOR_ARENA_WIN_NUM_TYPE = 1, //荣耀竞技场胜利次数 类型 完成X次巅峰竞技
	OPER_ACTIVITY_ITEM_EXPEDITION_FIGHTER = 2,   //完成X次远征战斗
	OPER_ACTIVITY_ITEM_TRAIN_MOUNT = 3,   //	完成X次坐骑驯养 不含可循环
	OPER_ACTIVITY_ITEM_HERO_DOOR = 4,   //英雄之门X次
	OPER_ACTIVITY_ITEM_TIME_ARENA = 5,   //组队竞技获胜X次
	OPER_ACTIVITY_ITEM_ARENA_WIN = 6,   //竞技场获胜X次
	OPER_ACTIVITY_ITEM_ALCHEMY_NUM = 7,   //炼金X次
	OPER_ACTIVITY_ITEM_WING_TRAIN = 8, //培养翅膀
	OPER_ACTIVITY_ITEM_TRAIN_MOUNT_DOUBLE = 9, //培养翅膀(可循环)

	OPER_ACTIVITY_ITEM_RECHARGE_ON_DAY = 10,	//充值任意/指定金额 并且 按活动开始第几日
	OPER_ACTIVITY_ITEM_RECHARGE_NUM = 11,	//充值任意/指定金额
	OPER_ACTIVITY_ITEM_LOGIN_DAILY_NUM = 12,	//累计登录任意/指定天
	OPER_ACTIVITY_ITEM_RECHARGE_NUM_AND_LOGIN_DAILY_NUM = 13,	//充值任意/指定金额 并且 累计登录指定天
	OPER_ACTIVITY_ITEM_WAR_NUM = 14,	//完成战场X次
	OPER_ACTIVITY_ITEM_TEAM_FB_NUM = 15,	//完成组队副本X次
	OPER_ACTIVITY_ITEM_WORLD_BOSS_PER = 16,	//世界BOSS达到X%伤害
	OPER_ACTIVITY_ITEM_GOLD_USE = 17,	//任意/指定钻石消费
	OPER_ACTIVITY_ITEM_EXCHANGE_ITEM = 18,	//兑换类型
	OPER_ACTIVITY_ITEM_WING_USE_DAN = 19,	//魔翼进阶消耗进阶丹
	OPER_ACTIVITY_ITEM_ARENA_NUM = 20,	//参与竞技场竞技次数

	OPER_ACTIVITY_ITEM_MOUNT_AND_START = 21,//指定坐骑升级到指定星星
	OPER_ACTIVITY_ITEM_WING_LEVEL = 22, //魔翼升到指定阶
	OPER_ACTIVITY_ITEM_ENCHANTING_NUM = 23,// 附魔任意/指定次数
	OPER_ACTIVITY_ITEM_RUNE_STONE_NUM = 24, //符石熔炼任意或指定次数

};

enum OPER_ACTIVITY_LISTEN_TYPE {
	OPER_ACTIVITY_LISTEN_TYPE_NUM = 1,
	OPER_ACTIVITY_LISTEN_TYPE_EXT1,
	OPER_ACTIVITY_LISTEN_TYPE_EXT2,
	OPER_ACTIVITY_LISTEN_TYPE_EXT3,
};

enum OPER_ACTIVITY_APPEND_TYPE {
	OPER_ACTIVITY_APPEND_BUFF_EFFECT = 1,//加buff效果
};

enum OPER_ACTIVITY_CONTENT_RECEIVE_TYPE {
	OPER_ACTIVITY_CONTENT_RECEIVE_ED = 1,//1.已经领取
	OPER_ACTIVITY_CONTENT_RECEIVE_CAN = 2,//2.可以领取
	OPER_ACTIVITY_CONTENT_RECEIVE_NO = 3,//3.不能领取
};


#endif /* OPER_ACTIVITY_DEF_H_ */
