/*
 * Active_Content_Def.h
 *
 *  Created on: 2014-06-25
 *      Author: xiaoliang
 */

#ifndef ACTIVE_CONTENT_DEF_H_
#define ACTIVE_CONTENT_DEF_H_

enum ACTIVE_CONTENT_RECEIVE_TYPE {
	ACTIVE_CONTENT_RECEIVE_ED = 1,//1.已经领取
	ACTIVE_CONTENT_RECEIVE_CAN = 2,//2.可以领取
	ACTIVE_CONTENT_RECEIVE_NO = 3,//3.不能领取
};

enum ACTIVE_CONTENT_RANK_RECEIVE_MAIL_ID {
	ACTIVE_CONTENT_RANK_RECEIVE_MAIL_LEVEL_RANK = 1020,//等级排名
	ACTIVE_CONTENT_RANK_RECEIVE_MAIL_ARENA_RANK = 1021,//单人竞技排名
	ACTIVE_CONTENT_RANK_RECEIVE_MAIL_FORCE_RANK = 1022,//战斗力排名
	ACTIVE_CONTENT_RANK_RECEIVE_MAIL_SG_RANK = 1042,//上古副本排名
	ACTIVE_CONTENT_RANK_RECEIVE_MAIL_MOUNT_RANK = 1053,//坐骑排名
	ACTIVE_CONTENT_RANK_RECEIVE_MAIL_WING_RANK = 1054,//翅膀排名
};

enum ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_ID {
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_WORLD_BOSS = 3007,//世界BOSS
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_SUIT_COLLECT_REWARD = 3004,//.套装收集2段,
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_HEROES_DOOR = 3008,//.英雄之门,
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_TEAM_ARENA = 3009, //.组队竞技,
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_WARER = 3010, //.战场,
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_REWARD_TASK = 3011,//悬赏,
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_SGFB = 3006,//上古副本
	//old
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_VIP_CLUB = 3002,//
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_LEVEL_ACE = 3003,//
	ACTIVE_CONTENT_CLOSE_RECEIVE_MAIL_GUILD_LEVEL = 3005,//
};

enum ACTIVE_CONTENT_MONGO_TYPE {
	ACTIVE_CONTENT_MONGO_SAVE = 1, //保存数据
	ACTIVE_CONTENT_MONGO_LOAD = 2, //加载数据
};

enum ACTIVE_CONTENT_REWARD_ACT_TYPE {
	ACTIVE_CONTENT_REWARD_ACT_TYPE_WORLD_BOSS = 1,//世界BOSS
	ACTIVE_CONTENT_REWARD_ACT_TYPE_SUIT_COLLECT_REWARD = 2,//.套装收集2段,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_HEROES_DOOR = 3,//.英雄之门,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_TEAM_ARENA = 4, //.组队竞技,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_WARER = 5, //.战场,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_REWARD_TASK = 6,//悬赏,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_SGFB = 7,//上古副本
	ACTIVE_CONTENT_REWARD_ACT_TYPE_FM_X_CI = 8,//.累计附魔X次
	ACTIVE_CONTENT_REWARD_ACT_TYPE_X_X_QUALITY_HEROER = 9,//累计X个X品质英雄,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_MOUNT_LVUP_X = 10,//10.坐骑进阶X次,
	ACTIVE_CONTENT_REWARD_ACT_TYPE_FUSION_X_ELITE = 11,//合成X张精英卡牌
	ACTIVE_CONTENT_REWARD_ACT_TYPE_REWARD_TASK_FS = 12,//悬赏大放送
	ACTIVE_CONTENT_REWARD_ACT_TYPE_GEM_UPGRADE = 13,//宝石升级

	ACTIVE_CONTENT_REWARD_ACT_TYPE_MOUNT_LEVELUP = 14,//坐骑培养 坐骑驯养
	ACTIVE_CONTENT_REWARD_ACT_TYPE_ALCHEMY_GIFT = 15,//炼金有礼

	ACTIVE_CONTENT_REWARD_ACT_TYPE_ACTIVITY_GIFT = 16,//活跃度好礼
	ACTIVE_CONTENT_REWARD_ACT_TYPE_RING_TASK = 17,//环任务奖励活动
	ACTIVE_CONTENT_REWARD_ACT_TYPE_DRAGON_PREY = 18,//龙谷掠夺活动
/********************************************************************************/
	ACTIVE_CONTENT_REWARD_ACT_TYPE_OPER_ACTIVITY_S = 10000,//特殊类型; 表示运营活动的所有类型
	ACTIVE_CONTENT_REWARD_ACT_TYPE_OPER_ACTIVITY = 99999,//特殊类型; 表示运营活动的所有类型

};

#endif /* ACTIVE_CONTENT_DEF_H_ */
