/*
 * Active_Def.h
 *
 *  Created on: 2014-06-25
 *      Author: xiaoliang
 */

#ifndef ACTIVE_DEF_H_
#define ACTIVE_DEF_H_

enum START_TYPE {
	START_ON_START_ZERO = 1,//1.开服时间0点
	START_ON_MERGER_ZERO = 2,//2.合服时间0点
	START_ON_START_TIME = 3,//3.开服时间
	START_ON_MERGER_TIME = 4,//4.合服时间
	START_ON_SET_TIME = 5,//5.以自定时间开始
	START_ON_START_NEXT_WEEK = 6,//6.以开服时间下星期
};

enum OPEN_TYPE {
	OPEN_ON_RANGE_WEEK = 1,//1.指定星期,eq:[1,3,5] 指定周一三五
	OPEN_ON_RANGE_DAY = 2,//2.指定日, eq:[1,6,20] 指定每月1号,6号,20号
	OPEN_ON_LOOP_DAY = 3,//3.日循环, eq:5, 间隔5天执行一次
	OPEN_ON_SET_TIME = 4,//4.指定日期, eq:2014-12-14, 指定的时间开启
	OPEN_ON_START_TYPE = 5,//5.按起始类型执行
};

enum ACTION_TYPE {
	ACTION_SEND_CLIENT_NOTICE = 1000, //通知客户端预告
	ACTION_OPEN_ICON = 1001,//开启图标
	ACTION_OPEN_ACTIVE = 1002,//开启活动
	ACTION_CLOSE_ICON = 2001,//关闭图标
	ACTION_CLOSE_ACTIVE = 2002,//关闭活动
	ACTION_SEND_CHAT = 3001,//消息广播
	ACTION_COUNT_RANK = 3002,//结算排行榜
};

enum ACTION_ARGV_TYPE {
	ACTION_ACTIVE_TAME_AREA = 10001,//组队竞技场
	ACTION_ACTIVE_WARER = 10002,//战场
	ACTION_ACTIVE_CAMPFIRE = 10003,//篝火舞会
	ACTION_ACTIVE_GANG_WARER = 10004,//公会战
	ACTION_ACTIVE_SECRET_SHOP = 10005,//神秘商人

	ACTION_ACTIVE_RECHARGE_REBATE = 70001,//充值返利活动
	ACTION_ACTIVE_RECHARGE_REBATE_DIY_TIME = 70009,//充值返利活动(自定义时间)

	ACTION_ACTIVE_LIMIT_BUY = 20001,//限时抢购
	ACTION_ACTIVE_VIP_CLUB = 20002,	//VIP俱乐部
	ACTION_ACTIVE_LEVEL_ACE = 20003,	//冲级活动
	ACTION_ACTIVE_SUIT_COLLECT = 20004,	//套装收集
	ACTION_ACTIVE_GUILD_LEVEL = 20005,	//公会升级

	ACTION_ACTIVE_LEVEL_RANK = 20006,	//等级排名
	ACTION_ACTIVE_ARENA_RANK = 20007,	//单人竞技排名
	ACTION_ACTIVE_FORCE_RANK = 20008,	//战力排名

	ACTION_ACTIVE_GEM_LEVELUP = 20009, //宝石升级
	ACTION_ACTIVE_WING_LEVELUP = 20010, //翅膀升级
	ACTION_ACTIVE_MOUNT_LEVELUP = 20011, //坐骑升级
	ACTION_ACTIVE_SG_RANK_PASS = 20012, //上古副本(rank)
	ACTION_ACTIVE_ARENA_DAN = 20013, //竞技场段位

	ACTION_ACTIVE_MOUNT_RANK = 20045, //坐骑排行
	ACTION_ACTIVE_WING_RANK = 20046, //翅膀排行

	ACTION_ACTIVE_CONTENT_WORLD_BOSS = 20014, //世界BOSS(开服活动)
	ACTION_ACTIVE_CONTENT_SUIT_COLLECT_TWO = 20015,//套装收集2
	ACTION_ACTIVE_CONTENT_HEROES_DOOR = 20016,//英雄之门
	ACTION_ACTIVE_CONTENT_ARENA_DAN_TWO = 20017,//竞技场2
	ACTION_ACTIVE_CONTENT_TEAM_ARENA = 20018,//组队竞技
	ACTION_ACTIVE_CONTENT_WARER = 20019,//战场
	ACTION_ACTIVE_CONTENT_REWARD_TASK = 20020,//悬赏
	ACTION_ACTIVE_CONTENT_SG_FB = 20021,//：上古副本
	ACTION_ACTIVE_CONTENT_TEAM_ARENA2 = 20022,//组队竞技2

	ACTION_ACTIVE_CONTENT_REWARD_TASK_FS = 20023,//悬赏大放送
	ACTION_ACTIVE_CONTENT_SG_WELFARE = 20024,//上古福利

	ACTION_ACTIVE_CONTENT_FM_X_CI = 20025,//累计附魔X次
	ACTION_ACTIVE_CONTENT_X_X_QUALITY_HEROER = 20026,//累计X个X品质英雄
	ACTION_ACTIVE_CONTENT_MOUNT_LVUP_X = 20027,//坐骑进阶X次
	ACTION_ACTIVE_CONTENT_FUSION_X_ELITE_CARD = 20028,//合成X张精英卡牌

	ACTION_ACTIVE_CONTENT_ONLINE_REWARD_GIFT = 20043,//在线礼包

	ACTION_ACTIVE_INVEST_PLAN = 70002, //投资计划
	ACTION_ACTIVE_THOR_LOTTERY = 70003, //博彩系统（雷神宝藏）
	ACTION_ACTIVE_TWO_RECHARGE = 70004, //全民充值
	ACTION_ACTIVE_FIRST_RECHARGE = 70005, //首充活动
	ACTION_ACTIVE_ANSWER_SYS = 10006, //智慧试炼
	ACTION_ACTIVE_DEFEND_DD = 10007,//守卫帝都
	ACTION_ACTIVE_WORLD_BOSS = 10008,//世界BOSS

	ACTION_ACTIVE_ACTIVITIES_STORES = 71001,//活动商城 情人节兑换商城
	ACTION_ACTIVE_RUNE_STONE_UP = 71002,//情人节符石
	ACTION_ACTIVE_NPC_RUNAWAY = 71003,//怪物暴动(情人节)

	ACTION_ACTIVE_LIMIT_TIME_RECHARGE = 70008, //限时充值
	ACTION_ACTIVE_OPER_ACTIVITY = 70010,//oper activity
	ACTION_ACTIVE_OPER_ACTIVITY_2 = 70011,//oper activity
};

enum ACTIVE_OPEN_STATUS {
	ACTIVE_NOT_OPEN_STATUS = 0,//已过期
	ACTIVE_WILL_OPEN_STATUS = 1,//未开启
	ACTIVE_OPEING_STATUS = 2,//进行中
};

#endif /* ACTIVE_DEF_H_ */
