/*
 * Vip_Def.h
 *
 *  Created on: 2014年7月21日
 *      Author: xiaoliang
 */

#ifndef VIP_DEF_H_
#define VIP_DEF_H_


enum VIP_COMMON_DEF {
	VIP_SEND_OPEN_MAIL_ID = 1012,//开通VIP的邮件ID
	VIP_SEND_CONTIUNE_MAIL_ID = 1014,//续费VIP的邮件ID
	VIP_SEND_EXPIRED_MAIL_ID = 1013,//过期VIP的邮件ID send_expired_vip_mail
	VIP_CURRENCY_ITEM_ID	= 21004401, //VIP币币ID
	VIP_SEND_INIT_OPEN_MAIL_ID = 1015,//初始开通送坐骑卡
	VIP_SEND_EXPERIENCE_MAIL_ID = 1018,//体验开通的邮件ID
	VIP_SEND_TURNTABLE_RECEIVE_MAIL_ID = 1017,//获取VIP转盘奖品邮件ID
	VIP_EXPERIENCE_CARD_HOURS = 25,//开通小时数下算体验开通
};

enum VIP_WORLD_TREE_TYPE {
	VIP_WORLD_TREE_SINGLE_EXPLORE = 1, //单人副本
	VIP_WORLD_TREE_TEAM_EXPLORE = 2, //组队推图
	VIP_WORLD_TREE_REWARD_TASK = 3, //悬赏任务
	VIP_WORLD_TREE_ARENA = 4, //竞技场
	VIP_WORLD_TREE_KNIGHT_TRIALS = 5, //骑士试炼
	VIP_WORLD_TREE_ROB_DRAGON = 6, //掠夺
	VIP_WORLD_TREE_RING_TASK = 7, //环任务
	VIP_WORLD_TREE_GAIN_DRAGON = 8, //龙谷收获
};

enum VIP_ACTIVE_STATUS {
	VIP_ACTIVE_OPEN = 1,//VIP开通
	VIP_ACTIVE_EXPIRED = 2, //vip过期
	VIP_ACTIVE_LEVEL_UP = 3, //VIP升级
	VIP_ACTIVE_READY_NOW = 4, //登陆通知
	VIP_ACTIVE_CONTIUNE = 5,//VIP续费
	VIP_ACTIVE_GROW_CHANGE = 6, //成长值变化
};

enum VIP_TURNTABLE_LOTTERY_TYPE {
	VIP_TURNTABLE_LOTTERY_ONE = 1,
	VIP_TURNTABLE_LOTTERY_ALL = 2,
};

#endif /* VIP_DEF_H_ */
