/*
 * Operating_Def.h
 *
 *  Created on: 2014年2月18日
 *      Author: linqiyou
 */

#ifndef OPERATING_DEF_H_
#define OPERATING_DEF_H_

enum {
	OPERATING_OFFLINE_MAIL = 1,
	OPERATING_OFFLINE_FRIEND = 2,
	OPERATING_OFFLINE_RECHARGE = 3,
	OPERATING_OFFLINE_FIREND_ADD = 4,
	OPERATING_OFFLINE_APPLY_HANDEL = 5,
	OPERATING_OFFLINE_GANGER_INFO = 6,
	OPERATING_OFFLINE_ARENA_THREE_DAY_REWARD = 7,
	OPERATING_OFFLINE_ARENA_SEVEN_DAY_REWARD = 8,
	OPERATING_OFFLINE_RECEIVE_FLOWERS = 9,
	OPERATING_OFFLINE_DRAGON_VALE_BUILDING = 10,
	OPERATING_OFFLINE_DRAGON_VALE_ROB_FIGHT_RESULT = 11,
	OPERATING_OFFLINE_DRAGON_VALE_GAIN_ROB_PRODUCTION = 12,
	OPERATING_OFFLINE_DRAGON_VALE_SPECIAL = 13,
	OPERATING_OFFLINE_INVITE_PLAYER = 14,
	OPERATING_OFFLINE_LIKE_SUCCESS = 15,
	OPERATING_OFFLINE_ACTIVE_CONTENT_LISTEN_WORLD_BOSS_END_INFO = 16,
	OPERATING_OFFLINE_TEAM_AWARD = 17,
};

#endif /* OPERATING_DEF_H_ */
