/*
 * Gang_Def.h
 *
 *  Created on: Jun 6, 2014
 *      Author: chenyulin
 */

#ifndef GANG_DEF_H_
#define GANG_DEF_H_

#define JUDGE_PLAYER(CONDITION) \
    if (! CONDITION) {\
        return -1;\
    }


enum GANG_INFO_LISTEN {
	GANG_INFO_LISTEN_OUT = 0,
	GANG_INFO_LISTEN_IN
};

enum GANG_INFO_LISTEN_UPDATE {
	GANG_ROW_INFO_ADD = 1,
	GANG_ROW_INFO_REMOVE,
	GANG_ROW_INFO_UPDATE
};

enum GANGER_HEADSHIP {
	GANG_HEADSHIP_NORMAL = 0,
	GANG_HEADSHIP_OFFICER,
	//GANG_HEADSHIP_ELDER,
	GANG_HEADSHIP_VICE,
	GANG_HEADSHIP_LEADER,
	GANG_HEADSHIP_END
};

enum GANGER_AUTHORITY_POS {
	GANGER_AU_ALLOW_ALL_IN = 0, // 1  允许所有人入会
	GANGER_AU_CHECK_IN, 		// 2  批准加入公会
	GANGER_AU_INVITE_IN,		// 3  邀请别人进入公会
	GANGER_AU_KICK_OUT,			// 4  踢出公会
	GANGER_AU_DISMISS,			// 5  解散公会
	GANGER_AU_RESIGN,			// 6  移交公会
	GANGER_AU_APPOINT,			// 7  任命下级成员官职
	GANGER_AU_BOSS_TIME,		// 8  决定boss时间
	GANGER_AU_FEAST_TIME,		// 9  决定公会盛宴时间
	GANGER_AU_UPGRADE_GANG,		// 10 升级公会
	GANGER_AU_UPGRADE_ADDON,	// 11 升级公会功能
	GANGER_AU_ORGANIZE_ACT,		// 12 号召帮众参与活动
	GANGER_AU_ASSIGN_SPOIL,		// 13 分配公会战奖励
	GANGER_AU_JOIN_ACT,			// 14 报名参加活动
	GANGER_AU_SEND_GROUP_MAIL,	// 15 发布群邮件
	GANGER_AU_SET_ANNOUNCE,		// 16 修改群公告
	GANGER_AU_END
};

enum GANG_JOIN_SETTING {
	GANG_IN_ALLALLOW = 0,
	GANG_IN_NEED_AGREE,
	GANG_IN_END
};

enum GANG_PASSED_EVENT_ID {
	GANG_PASSED_EVENT_WELLCOM = 101900,			// 欢迎XXXXX加入公会
	GANG_PASSED_EVENT_HEADSHIP = 101901,		// 授予XXXXXX长老/副帮主/官员的职位
	GANG_PASSED_EVENT_QUIT = 101902,			// XXXXX离开了公会
	GANG_PASSED_EVENT_KICK_OUT = 101903,		// 踢出了公会
	GANG_PASSED_EVENT_GANG_UPGRADE = 101904,	// 公会升级
	GANG_PASSED_EVENT_FUNC_UPGRADE = 101905,	// 公会建筑升级
	GANG_PASSED_EVENT_RESIGN = 101906,			// 公会转让
	GANG_PASSED_EVENT_SEIZE_POWER = 101907,		// 公会夺权
	GANG_PASSED_EVENT_RANK_CHANG = 101908,		// 公会排名
	GANG_PASSED_EVENT_DAILY_FUND_LACK = 101909,	// 公会维护费用不足
	GANG_PASSED_EVENT_SET_ANNOUNCE = 101910,	// 公会公告

//	GANG_PASSED_EVENT_DIAM_CONTRIB = 101906,	//钻石捐献
//	GANG_PASSED_EVENT_AMPLIFY_CONTRIB = 101907,	//附魔捐献
//	GANG_PASSED_EVENT_GOLD_CONTRIB = 101908,	//金币捐献
};

enum GANG_DONATE_TYPE {
	GANG_DONATE_TYPE_GOLD = 1,
	GANG_DONATE_TYPE_DIAM = 2
};

enum Gang_Action {
	GA_APPLY = 1,
	GA_AGREE = 1,
	GA_CANCEL = 2,
	GA_REFUSE = 2,
	GA_AGREE_ALL = 3,
	GA_REFUSE_ALL = 4,
};

enum Gang_Notify_Action {
	GNA_HAS_APPLY_TO_MANAGER = 1,
	GNA_HAS_INVITE_TO_INVITEE = 2,
	GNA_BE_AGREE_TO_APPLYER = 3,
	GNA_BE_REFUSE_TO_APPLYER = 4,
	GNA_AGREE_TO_INVITER = 5,
	GNA_REFUSE_TO_INVITER = 6,
	GNA_HEADSHIP_AUTH_TO_ASSIGNEE = 7,
	GNA_BLESS_BUF_TO_ACCEPTER = 8,
	GNA_NOTIFY_MEMBER_BE_SEIZED = 9,
};

enum Gang_Limit {
	MAX_GANG_LEVEL = 14,
	MAX_FUND_LACK_TIMES = 3,
};

enum Gang_Building_ID {
	BUILDING_BEGIN = 1,
	TOWER = 1,				// 技能塔
	ALTAR = 2,				// 祭坛
	SHOP = 3,				// 商店
	BUILDING_END
};

enum Gang_CD_Type {
	GCT_BEGIN = 1,
	GCT_GANG_LVL = 1,
	GCT_BUILDING_LVL = 2,
	GCT_END
};

enum Gang_War_Camp {
	CAMP_RED = 1,
	CAMP_BLUE = 2,
};
enum {
	GANG_WAR_ATTEND_NUMS = 16,

	GANG_WAR_STOP = 0,
	GANG_WAR_START = 1,
	GANG_WAR_READY = 2,
	GANG_WAR_CREATE_16 = 4,

	// 对战通知
	GANG_WAR_ATTEND			= 1023,
	GANG_WAR_FIGHT_ONE		= 1024,
	GANG_WAR_FIGHT_THREE	= 1025,
	GANG_WAR_FIGHT_FIVE		= 1026,
	GANG_WAR_FIGHT_SEVEN	= 1034,

	// 轮空通知
	GANG_WAR_FIGHT_EMPTY_ONE	= 1027,
	GANG_WAR_FIGHT_EMPTY_THREE	= 1028,
	GANG_WAR_FIGHT_EMPTY_FIVE	= 1029,
	GANG_WAR_FIGHT_EMPTY_SEVEN	= 1033,

	GANG_WAR_ATTEND_AWARD = 1035, // 参与奖励
	GANG_WAR_AWARD_ASSIGN = 1036, // 奖励分配
	GANG_WAR_RANK_AWARD	= 1039, // 公会战排名奖励
	GANG_WAR_RANK_AWARD_GET = 1040, // 排名奖励通知领取
	GANG_WAR_NO_BATTLE_AWARD = 1041, // 参与奖励
};

#endif /* GANG_DEF_H_ */
